課題15 model spec作成
aiandrox/sample_app_for_rspec pull request #2
Opened 2020-02-03 09:09 UTC by Aiandrox

## 概要

<img width="699" alt="スクリーンショット 2020-02-03 18 04 32" src="https://user-images.githubusercontent.com/44717752/73639736-4429cd00-46b0-11ea-972f-665bb36b9bff.png">

## 確認方法

1. Gem を追加したので `bundle install` を実行してください

## 影響範囲

・gemfile
・config.initializer

## チェックリスト

- [ ] siderをパスした
- [ ] 必要なgemを追加した
- [ ] rescue_fromでエラーをキャッチした
- [ ] エラーに応じた例外処理をErrorHandlerに追加した
- [ ] エラーに応じたステータスを返し、テンプレートを表示するようにした
- [ ] 500エラーのときにはslack通知を行うようにした
- [ ] WebhookURLに指定するURL情報は、credentialsに記述（していない）

## コメント

2020-02-03 09:26 UTC, yuji91 commented on spec/models/task_spec.rb
> +    let(:new_task) { Task.new(title: title, status: status) }
インスタンスを作るだけであれば`FactoryBot.build`が使用できます。

2020-02-03 09:31 UTC, yuji91 commented on spec/models/task_spec.rb
> +    it 'タイトルが重複する場合 無効' do
`context`作る形で他と統一した方がいいですね

2020-02-03 09:33 UTC, yuji91 commented on spec/models/task_spec.rb
> +      expect(new_task).to be_invalid
`task_with_duplicated_title = build(:task, title: task.title)`と既に作成したタイトルを使ってインスタンスを作成することを明示した方が分かりやすいかなと思います。

2020-02-03 09:34 UTC, yuji91 requested changes
コメントしました！

2020-02-03 09:35 UTC, yuji91 commented
> enumで設定されていない値が入力された場合のテストを書こうと思ったのですが、status: 'not_set'と入れた時点でエラーが出るようでした。（コメントアウトで書いています。無理なようでしたら削除します）
この項目をテストすることは不可能ということでしょうか？

元々 statusはintegerが入るカラムなので、enumと紐づいていないただのStringである文字列の登録は出来ないと思います！

2020-02-03 10:15 UTC, Aiandrox commented
<img width="709" alt="スクリーンショット 2020-02-03 19 08 41" src="https://user-images.githubusercontent.com/44717752/73644393-a5559e80-46b8-11ea-94f8-58a144c310f1.png">

https://qiita.com/jiz/items/0cd302bb16ce55d231cb
を参考に実装してみました！

2020-02-03 10:16 UTC, Aiandrox commented on spec/models/task_spec.rb
> +      expect(new_task).to be_invalid
ba4d2cf で修正しました！

2020-02-03 10:16 UTC, Aiandrox commented on spec/models/task_spec.rb
> +    it 'タイトルが重複する場合 無効' do
ba4d2cf で修正しました！

2020-02-03 10:16 UTC, Aiandrox commented on spec/models/task_spec.rb
> +    let(:new_task) { Task.new(title: title, status: status) }
ba4d2cf で修正しました！

2020-02-03 10:19 UTC, yuji91 commented
`[Fix] 書き換え`だと修正コミットの粒度が大きいと思うので、指摘事項毎に分けたほうが良いかと思います！（次回からで大丈夫です）

2020-02-03 10:23 UTC, yuji91 reviewed
`let!(:task_with_duplicated_title)`が対象の`context`内のみ影響するか確認をお願いします！

2020-02-03 10:33 UTC, Aiandrox commented
<img width="682" alt="スクリーンショット 2020-02-03 19 27 00" src="https://user-images.githubusercontent.com/44717752/73645737-3b8ac400-46bb-11ea-9d88-2392cf9b4b13.png">
contextの外では影響しないようです！

itの中に入れてしまうなら、`create(:task)`で書いて、itの外（beforeの代わり）ならletで書くという感じですかね？

2020-02-04 08:50 UTC, yuji91 commented
> itの中に入れてしまうなら、create(:task)で書いて、itの外（beforeの代わり）ならletで書くという感じですかね？

その認識で大丈夫です！🙆‍♀️

2020-02-04 09:10 UTC, yuji91 commented on spec/models/task_spec.rb
> +      let!(:task_with_duplicated_title) { create(:task) }
このletが実行される時はtaskの初回作成時となるので、task_with_duplicated_titleという変数名は正確ではないように思えます。 初回にtaskが作成され、次にtaskを作成する際にtitleが重複しているオブジェクトを格納する変数が`task_with_duplicated_title`であるべきだと思います。

そのため下記の方が自然かなと思います。
```
task = create(:task) # または let!(:task) { create(:task) }
task_with_duplicated_title = build(:task, title: task.title)
expect(task_with_duplicated_title).to be_invalid
```

2020-02-04 09:12 UTC, yuji91 requested changes
コメントしました！

2020-02-04 09:29 UTC, Aiandrox commented
<img width="690" alt="スクリーンショット 2020-02-04 18 26 25" src="https://user-images.githubusercontent.com/44717752/73731680-40637c80-477c-11ea-8019-3fb0f6a65e7e.png">

2020-02-04 09:29 UTC, Aiandrox commented on spec/models/task_spec.rb
> +      let!(:task_with_duplicated_title) { create(:task) }
3518773 で修正しました！

2020-02-04 09:37 UTC, yuji91 commented on spec/factories/tasks.rb
> +    title { 'タイトル' }
`sequence`を使ってFactoryを複数回作成した際にValidationエラーで失敗しないようにしておきたいです。
`create_list`でFactoryを複数作るケースはよく使われるので、それに耐えうる形でFactoryを定義した方が良いです。

2020-02-04 09:37 UTC, yuji91 requested changes
コメントしました！

2020-02-04 10:11 UTC, Aiandrox commented on spec/factories/tasks.rb
> +    title { 'タイトル' }
ecdba23 f3cc3ca で修正しました！
この場合、重複をテストするときにわかりづらい気がするので、明示的に`let(:title) { 'title_1' }`と入れた方がわかりやすいでしょうか？

2020-02-04 10:28 UTC, yuji91 commented on spec/factories/tasks.rb
> +  sequence(:title, "title_1")
多分この状態だと複数件`create(:task)`を実行した場合にValidationエラーでFactoryの作成が失敗してしまうと思います。
`sequence(:title) { |n| "title-#{n}" }`と、index番号を使って作成するtaskのタイトルが常に一意になるようにしておきましょう。

2020-02-04 10:37 UTC, Aiandrox commented on spec/factories/tasks.rb
> +  sequence(:title, "title_1")
448552e で修正しました！

2020-02-04 11:39 UTC, yuji91 approved these changes
LGTM!

2020-02-04 11:59 UTC, merged